(require 'ox-publish)
(require 'eob-utils)


(defun eob-get-entry(org-file)
  (interactive)
  (with-temp-buffer
    (insert-file-contents org-file nil 0 500)
    (org-html-export-as-html nil nil nil t nil)
    (setq org-html (substring-no-properties (car kill-ring)))
    (setq content (org-html-get-content-without-toc org-html))
  )
)

(defun eob-generate-index(base-dir site-sub-dir)
  (interactive)
  (let* ((post-list-all (eob-get-posts-with-properties base-dir site-sub-dir)))
    (setq N_all  (length post-list-all))
    (setq n_list (float eob-page-per-index))
    (setq N_page (ceiling (/ N_all n_list)))
    (setq index_n 0)
    (while (< index_n N_page)
      (if (equal index_n 0) (setq index_file_name "index.html") (setq index_file_name (format "index/%s/index.html" index_n)) )
      (setq index_file_name (expand-file-name index_file_name eob-publish-directory))
      (make-directory (file-name-directory index_file_name) t)
      (setq enable-page-pre t)
      (setq enable-page-next t)
      (setq page-next (format "/index/%s/" (1+ index_n)))
      (setq page-pre (format "/index/%s/" (1- index_n)))
      (if (equal index_n 1)  (setq page-pre "/index.html"))
      (if (equal index_n 0) (setq enable-page-pre nil))
      (if (= index_n (1- N_page)) (setq enable-page-next nil))
      (setq post-list-ht (list ()))
      (setq i 0)
      (while (< i n_list)
        (setq post-num (ceiling (+ (* n_list index_n) i)))
	(setq post-this  (nth post-num post-list-all))
        (cond ( (< post-num N_all)
      		(setq org-file (ht-get post-this "org-file-full-path"))
        	(setq entry-part (eob-get-entry org-file))
		(add-to-list 'post-list-ht (ht-merge post-this (ht ("post-entry" entry-part))))))
      	(setq i (1+ i))
      )
    (setq content-all (ht-create))
    (ht-set content-all "post-title" "Index")
    (ht-set  content-all "post-list" (reverse (butlast post-list-ht)))
    (ht-set  content-all "enable-page-pre" enable-page-pre)
    (ht-set  content-all "enable-page-next" enable-page-next)
    (ht-set  content-all "page-pre" page-pre)
    (ht-set  content-all "page-next" page-next)
    (ht-set content-all "head" (eob-generate-head nil "Home"))
    (ht-set content-all "navigation" (eob-generate-navigation))
    (setq content-all (ht-merge content-all (eob-get-common-info)))
    (with-temp-buffer
     (insert (eob-render "index.html" content-all))
     (when (file-writable-p index_file_name)
        (write-region (point-min)
                      (point-max)
		      index_file_name)))
    (setq index_n (1+ index_n))))
  ; (kill-buffer "*Org HTML Export*")
)
  

(provide 'eob-generator-index)
